# Generated by Django 5.2 on 2025-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='confirmado',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
