# Generated by Django 5.2 on 2025-06-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='duracion',
            field=models.CharField(max_length=100),
        ),
    ]
