# Generated by Django 5.2 on 2025-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('especialista', 'Especialista'), ('empleado', 'Empleado')], max_length=20),
        ),
    ]
