# Generated by Django 5.2 on 2025-05-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_clientes_prueba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.AddField(
            model_name='clientes',
            name='genero1',
            field=models.CharField(default=' passwword ', max_length=10),
            preserve_default=False,
        ),
    ]
