# Generated by Django 5.2 on 2025-06-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servicios_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
