# Generated by Django 5.2 on 2025-05-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_contraseña_clientes_password_clientes_genero1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='fechaNac',
            field=models.DateField(auto_now_add=True),
        ),
    ]
